celsius = int(input('Enter the temparature in in Celsius: '))
print('in Fahrenheit that is', celsius * 9/5 + 32)

teamname = input('Enter the Team Name: ')
Match1GS = int(input('Goals Scored in Match #1: '))
Match1GA = int(input('Goals Against in Match #1: '))
Match2GS = int(input('Goals Scored in Match #2: '))
Match2GA = int(input('Goals Against in Match #2: '))
Match3GS = int(input('Goals Scored in Match #3: '))
Match3GA = int(input('Goals Against in Match #3: '))
Match4GS = int(input('Goals Scored in Match #4: '))
Match4GA = int(input('Goals Against in Match #4: '))
Match5GS = int(input('Goals Scored in Match #5: '))
Match5GA = int(input('Goals Against in Match #5: '))
print(teamname)
input('Wins: ')
input('Draws: ')
input('Losses: ')
input('Points: ')

